/*
 * TodoList RESTful API
 * OpenAPI for TodoList RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: yogadimaspambudi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.api;

import io.swagger.client.model.ArrayTodolist;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;


/**
 * API tests for AllApi
 */
@Ignore
public class AllApiTest {

    private final AllApi api = new AllApi();

    /**
     * Get All Todolist
     *
     * Get all active todolist by default
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void todolistGetTest() throws Exception {
        Boolean includeDone = null;
        String name = null;
        ArrayTodolist response = api.todolistGet(includeDone, name);

        // TODO: test validations
    }
}
