/**
 * TodoList RESTful API
 * OpenAPI for TodoList RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: yogadimaspambudi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.apis

import io.swagger.client.models.ArrayTodolist

import io.swagger.client.infrastructure.*

class AllApi(basePath: kotlin.String = "https://{environment}.yogadimaspambudi.com/api/v1") : ApiClient(basePath) {

    /**
     * Get All Todolist
     * Get all active todolist by default
     * @param includeDone Is include_done todolist (optional, default to false)
     * @param name Filter todolist by name (optional)
     * @return ArrayTodolist
     */
    @Suppress("UNCHECKED_CAST")
    fun todolistGet(includeDone: kotlin.Boolean? = null, name: kotlin.String? = null): ArrayTodolist {
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>().apply {
            if (includeDone != null) {
                put("include_done", listOf(includeDone.toString()))
            }
            if (name != null) {
                put("name", listOf(name.toString()))
            }
        }
        val localVariableConfig = RequestConfig(
                RequestMethod.GET,
                "/todolist", query = localVariableQuery
        )
        val response = request<ArrayTodolist>(
                localVariableConfig
        )

        return when (response.responseType) {
            ResponseType.Success -> (response as Success<*>).data as ArrayTodolist
            ResponseType.Informational -> TODO()
            ResponseType.Redirection -> TODO()
            ResponseType.ClientError -> throw ClientException((response as ClientError<*>).body as? String ?: "Client error")
            ResponseType.ServerError -> throw ServerException((response as ServerError<*>).message ?: "Server error")
        }
    }
}
