/**
 * TodoList RESTful API
 * OpenAPI for TodoList RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: yogadimaspambudi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param name 
 * @param priority 
 * @param tags 
 */
data class CreateOrUpdateTodolist (

    val name: kotlin.String,
    val priority: java.math.BigDecimal,
    val tags: kotlin.Array<kotlin.String>? = null
) {
}