/**
 * TodoList RESTful API
 * OpenAPI for TodoList RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: yogadimaspambudi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
package io.swagger.client.models


/**
 * 
 * @param success 
 */
data class InlineResponse200 (

    val success: kotlin.Boolean? = null
) {
}