/*
 * TodoList RESTful API
 * OpenAPI for TodoList RESTful API
 *
 * OpenAPI spec version: 1
 * Contact: yogadimaspambudi@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.47
 *
 * Do not edit the class manually.
 *
 */
import {ApiClient} from "../ApiClient";
import {ArrayTodolist} from '../model/ArrayTodolist';

/**
* All service.
* @module api/AllApi
* @version 1
*/
export class AllApi {

    /**
    * Constructs a new AllApi. 
    * @alias module:api/AllApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instanc
    e} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }

    /**
     * Callback function to receive the result of the todolistGet operation.
     * @callback moduleapi/AllApi~todolistGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/ArrayTodolist{ data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All Todolist
     * Get all active todolist by default
     * @param {Object} opts Optional parameters
     * @param {Boolean} opts.includeDone Is include_done todolist (default to <.>)
     * @param {String} opts.name Filter todolist by name
     * @param {module:api/AllApi~todolistGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link <&vendorExtensions.x-jsdoc-type>}
     */
    todolistGet(opts, callback) {
      opts = opts || {};
      let postBody = null;

      let pathParams = {
        
      };
      let queryParams = {
        'include_done': opts['includeDone'],'name': opts['name']
      };
      let headerParams = {
        
      };
      let formParams = {
        
      };

      let authNames = ['TodolistAuth'];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = ArrayTodolist;

      return this.apiClient.callApi(
        '/todolist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

}